### ISSUE TITLE
Artix 7移植失败

### ISSUE THREAD

**Issue by bevischenoast** [rongcuid/MSCC#2]
我自己移植失败, 希望可以放出您的可移植版本, 非常感谢
我的环境是 Windows下的Vivado

**Comment by rongcuid** [comment]
这个可以移植的，毕竟我自己就是用Artix-7。你得确认下针脚对不对，毕竟不同板子针脚配置不同。

其他的话，具体得看看你有啥错，贴一下错误信息、截图等。

**Comment by bevischenoast** [comment]
时钟模块是怎么处理的呢, 我是用的Clocking Wizard, 直接导入您的目录Vivado会提示找不到模块clk_gb:xil_defaultlib.SB_GB

**Comment by rongcuid** [comment]
我应该没有使用 Clocking Wizard。具体有点久远我不记得了，但是我的板子的配置文件里面有一个100MHz的时钟输入针脚，我将它引到了一个Global Buffer (SB_GB)上面用来供应整个设计的时钟。你的板子怎么样我不知道，你得看板子的文档和例程，可能需要你自己修改时钟代码。

**Comment by bevischenoast** [comment]
您好,
我使用Clock Wizard修改完代码后是这个样子的:
Clk_in 连接板子上的50MHz时钟, 引入SB_GB, 然后SB_GB输出100Mhz的时钟给 CPU_TOP,
最终实现的时候Vivado报告时序slack.

真的是麻烦你了.
可以加微信交流吗

________________________________
发件人: Rongcui Dong <notifications@github.com>
发送时间: Wednesday, September 25, 2019 3:37:41 AM
收件人: rongcuid/MSCC <MSCC@noreply.github.com>
抄送: bevischenoast <BEVISCHEN@LIVE.COM>; Author <author@noreply.github.com>
主题: Re: [rongcuid/MSCC] Artix 7移植失败 (#2)


我应该没有使用 Clocking Wizard。具体有点久远我不记得了，但是我的板子的配置文件里面有一个100MHz的时钟输入针脚，我将它引到了一个Global Buffer (SB_GB)上面用来供应整个设计的时钟。你的板子怎么样我不知道，你得看板子的文档和例程，可能需要你自己修改时钟代码。

―

**Comment by rongcuid** [comment]
哈哈，微信就免了吧，我就一个号。有什么问题可以继续开Issue
