### ISSUE TITLE
Make出错，是因为没链接的原因吗

### ISSUE THREAD

**Issue by bevischenoast** [rongcuid/MSCC#3]
cd riscv-compliance && make clean && make
make[1]: Entering directory '/home/bevis/MSCC/riscv-compliance'
make \
	RISCV_TARGET=msc-02 \
	RISCV_DEVICE=rv32i \
	RISCV_PREFIX=riscv64-unknown-elf- \
	clean -C /home/bevis/MSCC/riscv-compliance/riscv-test-suite/rv32i
make[2]: Entering directory '/home/bevis/MSCC/riscv-compliance/riscv-test-suite/rv32i'
rm -rf /home/bevis/MSCC/riscv-compliance/work
make[2]: Leaving directory '/home/bevis/MSCC/riscv-compliance/riscv-test-suite/rv32i'
make[1]: Leaving directory '/home/bevis/MSCC/riscv-compliance'
make[1]: Entering directory '/home/bevis/MSCC/riscv-compliance'
for isa in rv32i; do \
	echo $isa; \
	make RISCV_TARGET=msc-02 RISCV_DEVICE=$isa RISCV_ISA=$isa variant; \
                rc=$?; \
                if [ $rc -ne 0 ]; then \
		exit $rc; \
	fi \
done
rv32i
make[2]: Entering directory '/home/bevis/MSCC/riscv-compliance'
make \
	RISCV_TARGET=msc-02 \
	RISCV_DEVICE=rv32i \
	RISCV_PREFIX=riscv64-unknown-elf- \
	run -C /home/bevis/MSCC/riscv-compliance/riscv-test-suite/rv32i
make[3]: Entering directory '/home/bevis/MSCC/riscv-compliance/riscv-test-suite/rv32i'
riscv64-unknown-elf-gcc -march=rv32i -mabi=ilp32 -Wl,--build-id=none -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -I/home/bevis/MSCC/riscv-compliance/riscv-test-env/ -I/home/bevis/MSCC/riscv-compliance/riscv-test-env/msc/ -I/home/bevis/MSCC/riscv-compliance/riscv-target/msc-02/ -T/home/bevis/MSCC/riscv-compliance/riscv-test-env/msc/link.ld src/I-ENDIANESS-01.S -o /home/bevis/MSCC/riscv-compliance/work/rv32i/I-ENDIANESS-01.elf; riscv64-unknown-elf-objdump -D /home/bevis/MSCC/riscv-compliance/work/rv32i/I-ENDIANESS-01.elf > /home/bevis/MSCC/riscv-compliance/work/rv32i/I-ENDIANESS-01.elf.objdump; riscv64-unknown-elf-objcopy -O binary /home/bevis/MSCC/riscv-compliance/work/rv32i/I-ENDIANESS-01.elf /home/bevis/MSCC/riscv-compliance/work/rv32i/I-ENDIANESS-01.elf.bin
/bin/sh: riscv64-unknown-elf-gcc: command not found
/bin/sh: riscv64-unknown-elf-objdump: command not found
/bin/sh: riscv64-unknown-elf-objcopy: command not found
make[3]: *** [Makefile:47: I-ENDIANESS-01.elf] Error 127
make[3]: Leaving directory '/home/bevis/MSCC/riscv-compliance/riscv-test-suite/rv32i'
make[2]: *** [Makefile:48: simulate] Error 2
make[2]: Leaving directory '/home/bevis/MSCC/riscv-compliance'
make[1]: *** [Makefile:38: all_variant] Error 2
make[1]: Leaving directory '/home/bevis/MSCC/riscv-compliance'
make: *** [Makefile:12: run_compliance] Error 2

**Comment by rongcuid** [comment]
你路径里面没有编译器。你确认一下开发环境配好了吗？README的环境变量也检查下。

**Comment by rongcuid** [comment]
后续问题再重开
